### ISSUE TITLE
Tech Reborn Alloy Furnace

### ISSUE THREAD

**Issue by Servovicis** [Wurmatron/WurmTweaks#54] opened 2016-07-30 15:21 UTC
All Furnace recipes are broken for Tech Reborn Alloy Furnace

This also makes red alloy uncraftable as its the only furnace that shows a recipe.

**Comment by Wurmatron** [comment] 2016-08-01 19:36
Seems to be caused by Alloy Smelter built in Ore Dictionary, this will require an lot of work to fix.

**Comment by Servovicis** [comment] 2016-08-01 21:58
Anything that doesn't require that level of tech tree could be moved to other alloy methods like induction furnace and Alloy Smelter. Stuff like redwire alloy

**Comment by Wurmatron** [comment] 2016-08-02 15:30
This issue / recipes will be fixed within the next release of the modpack.

**Closed as completed by Wurmatron** 2016-08-02 15:30 UTC
Labels: Derp
